name: Bug Report
description: Report a bug in xlsx-format
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code to reproduce the issue.
      render: typescript
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: xlsx-format version
      placeholder: e.g. 1.0.0
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g. 22.0.0
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Attach the .xlsx file if relevant, or add any other context.
