"""Generate the semicolon-terminated WHATWG named character reference table.

Source: https://html.spec.whatwg.org/multipage/named-characters.html
Python's html.entities.html5 provides the standard-library copy used here.
"""

import json
import re
from html.entities import html5
from pathlib import Path


root = Path(__file__).resolve().parent.parent
output = root / "src" / "api" / "html-entities.ts"
entities = [(name[:-1], value) for name, value in sorted(html5.items()) if name.endswith(";")]
lines = [
	"/**",
	" * Generated by `python3 scripts/generate-html-entities.py` from Python's `html.entities.html5`.",
	" * Source: https://html.spec.whatwg.org/multipage/named-characters.html",
	" * Do not edit manually.",
	" */",
	"export const HTML_ENTITY_VALUES: Readonly<Record<string, string>> = {",
]
for name, value in entities:
	key = name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)
	encoded_value = "'\"'" if value == '"' else json.dumps(value, ensure_ascii=True)
	lines.append(f"\t{key}: {encoded_value},")
lines.append("};")
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
